In [1]:
import math
import numpy as np
import pandas as pd

import japanize_matplotlib
import matplotlib.pyplot as plt

# 演習問題7.1

In [17]:
df = pd.DataFrame([[13, 5, 5, 3, 4, 18], [378, 200, 151, 47, 31, 33]])
df.columns = [
    f"放射線量_{v}" for v in ["0", "1-9", "10-49", "50-99", "100-199", "200+"]
]
df = pd.concat([df, df.sum().to_frame().T])
df.index = ["白血病", "その他のがん", "合計"]
df.index.name = "死因"

In [33]:
df.T

,放射線量_0,放射線量_1-9,放射線量_10-49,放射線量_50-99,放射線量_100-199,放射線量_200+
死因,,,,,,
白血病,13,5,5,3,4,18
その他のがん,378,200,151,47,31,33
合計,391,205,156,50,35,51


In [35]:
df_tmp = df.T
y = (df_tmp["白血病"] / df_tmp["合計"]).values
X = np.stack([np.ones(len(y)), list(range(1, 7))])
n = df_tmp["合計"].values

In [41]:
n

array([391, 205, 156,  50,  35,  51])

In [78]:
def pred_pi(beta, X):
    z = beta @ X
    return np.exp(z) / (1 + np.exp(z))


# 初期値
beta = np.array([0.0, 0.0])

for _ in range(10):
    # piの推定
    pi = pred_pi(beta, X)  # shape (N,)

    # スコアの推定 (2,)
    U = np.sum((y - n * pi) * X, axis=1)  # Xの各行で重み付き和

    # 情報行列の推定 (2x2)
    W = n * pi * (1 - pi)  # shape (N,)
    J = X @ (W[:, None] * X.T)  # 2xN @ N×2 = 2x2
    beta = beta + np.linalg.inv(J) @ U

In [79]:
beta

array([-10.81132773,   0.97888537])

In [50]:
y

array([0.03324808, 0.02439024, 0.03205128, 0.06      , 0.11428571,
       0.35294118])

In [51]:
n

array([391, 205, 156,  50,  35,  51])

In [53]:
y - n * pi

array([-195.46675192, -102.47560976,  -77.96794872,  -24.94      ,
        -17.38571429,  -25.14705882])

In [60]:
n * pi * (1 - pi)

array([97.75, 51.25, 39.  , 12.5 ,  8.75, 12.75])