In [2]:
import numpy as np
import pandas as pd

## 8.3.1の再現

In [12]:
# 表8.1のデータ
df = pd.DataFrame(
    {
        "性別" : ["女性", "女性", "女性", "男性", "男性", "男性"],
        "年齢" : ["18-23", "24-40", ">40", "18-23", "24-40", ">40"],
        "重要でない/あまり重要でない": [26, 9, 5, 40, 17, 8],
        "重要": [12, 21, 14, 17, 15, 15],
        "非常に重要": [7, 15, 41, 8, 12, 18]
    }
)

In [13]:
df

,性別,年齢,重要でない/あまり重要でない,重要,非常に重要
0,女性,18-23,26,12,7
1,女性,24-40,9,21,15
2,女性,>40,5,14,41
3,男性,18-23,40,17,8
4,男性,24-40,17,15,12
5,男性,>40,8,15,18


In [19]:
# 反応の基準カテゴリーは、「重要でない/あまり重要でない」と設定
# 説明変数の基準カテゴリーは、「女性」、「年齢18-23歳」を設定
X = pd.get_dummies(df).astype(int)[["性別_男性", "年齢_24-40", "年齢_>40"]].values
intercept = np.vstack(np.ones(len(X)))
X = np.hstack([intercept, X])

In [81]:
y = df[["重要でない/あまり重要でない","重要","非常に重要"]]
y = y.values

In [84]:
n = y.sum(axis = 1)

#### piの計算

In [77]:
def logit1(beta2, beta3, X):
    return 1/ (1 + (X*beta2).sum(axis = 1) + (X*beta3).sum(axis = 1))

def logit2(beta2, beta3, X):
    return (X*beta2).sum(axis = 1) / (1 + (X*beta2).sum(axis = 1) + (X*beta3).sum(axis = 1))

def logit3(beta2, beta3, X):
    return (X*beta3).sum(axis = 1) / (1 + (X*beta2).sum(axis = 1) + (X*beta3).sum(axis = 1))

In [123]:
beta02 = 1
beta12 = 1
beta22 = 1
beta32 = 1

beta03 = 1
beta13 = 1
beta23 = 1
beta33 = 1

beta2 = np.array([beta02, beta12, beta22, beta32])
beta3 = np.array([beta03, beta13, beta23, beta33])

pi_i1 = logit1(beta2, beta3, X)
pi_i2 = logit2(beta2, beta3, X)
pi_i3 = logit3(beta2, beta3, X)

pi = np.stack([pi_i1, pi_i2, pi_i3]).reshape(6, 3)

num = X[:, 1:]*(y - n.reshape(6, 1)* np.stack([pi_i1, pi_i2, pi_i3]).reshape(6, 3))
denom = 1 - pi
U = (num/denom).sum(axis = 0)


In [124]:
U

array([12.83333333, 12.66666667, 29.08333333])

In [130]:
n.reshape(6, 1)

array([[45],
       [45],
       [60],
       [65],
       [44],
       [41]])

In [128]:
pi

array([[0.33333333, 0.2       , 0.2       ],
       [0.2       , 0.14285714, 0.14285714],
       [0.33333333, 0.4       , 0.4       ],
       [0.4       , 0.42857143, 0.42857143],
       [0.33333333, 0.4       , 0.4       ],
       [0.4       , 0.42857143, 0.42857143]])

In [131]:
n.reshape(6, 1)*pi

array([[15.        ,  9.        ,  9.        ],
       [ 9.        ,  6.42857143,  6.42857143],
       [20.        , 24.        , 24.        ],
       [26.        , 27.85714286, 27.85714286],
       [14.66666667, 17.6       , 17.6       ],
       [16.4       , 17.57142857, 17.57142857]])

In [ ]:
n.reshape(6, 1)*pi*