In [1]:
import numpy as np
import pandas as pd
from tqdm import tqdm
from scipy.stats import norm

In [2]:
df = pd.DataFrame({
    "y": [65, 156, 100, 134, 16, 108, 121, 4, 39,
          143, 56, 26, 22, 1, 1, 5, 65],
    "x": [3.36, 2.88, 3.63, 3.41, 3.78, 4.02, 4.00, 4.23, 3.73,
          3.85, 3.97, 4.51, 4.54, 5.00, 5.00, 4.72, 5.00]
})

In [62]:
J = np.array(
    [
        [len(df), df["x"].sum()],
        [df["x"].sum(), (df["x"]**2).sum()]
    ]
)

beta = np.zeros(2)
tol = 1e-8
max_iter = 1000
for j in tqdm(range(max_iter)):
    
    mu_i = np.exp(beta[0] + beta[1] * df["x"])
    
    U = np.array(
        [
            ((df["y"] - mu_i) / mu_i).sum(),
            (((df["y"] - mu_i) / mu_i) * df["x"]).sum()
        ]
    )

    delta = np.linalg.inv(J) @ U
    beta_new = beta + delta

    # 収束判定
    if np.linalg.norm(beta_new - beta, ord=2) < tol:
        beta = beta_new
        print(f"Converged at iteration {j+1}")
        break

    beta = beta_new.copy()

  9%|██████████▍                                                                                                        | 91/1000 [00:00<00:00, 1926.38it/s]

Converged at iteration 92


In [49]:
J

array([[ 17.    ,  69.63  ],
       [ 69.63  , 291.4571]])

In [50]:
beta

array([ 8.47749765, -1.10929792])

In [63]:
z = norm.ppf(0.975)
z

np.float64(1.959963984540054)

array([1.65480771, 0.39965447])

In [88]:
std_error = np.sqrt(np.diag(np.linalg.inv(J)))
#std_error = np.array(results_exp.bse)

In [92]:
lower95 = np.round(beta - z * std_error, 4)
upper95 = np.round(beta + z * std_error, 4)
(lower95[0], upper95[0]), (lower95[1], upper95[1])

((np.float64(5.2341), np.float64(11.7209)),
 (np.float64(-1.8926), np.float64(-0.326)))

In [ ]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

model_exp = smf.glm(
    formula="y ~ x",
    data=df,
    family=sm.families.Gamma(link=sm.families.links.log())
)
results_exp = model_exp.fit()

In [85]:
np.array(results_exp.bse)

array([1.60342638, 0.38724531])

In [97]:
l_max = (np.log(1/mu_i) - df["y"] * (1/mu_i)).sum()
l_null = 

np.float64(-83.87704628043076)

In [122]:
D_0 = 2 * np.sum(df["y"] / df["y"].mean() - np.log(df["y"] / df["y"].mean()) - 1)
D_1 = 2 * np.sum(df["y"] / np.exp(beta[0] + df["x"] * beta[1]) - np.log(df["y"] / np.exp(beta[0] + df["x"] * beta[1])) - 1)
delta_D = D_0 - D_1

In [125]:
D_0, D_1, delta_D

(np.float64(26.282098643354615),
 np.float64(19.456532040863426),
 np.float64(6.82556660249119))

In [124]:
delta_D

np.float64(6.82556660249119)