In [2]:
import numpy as np
import pandas as pd

# 演習問題11.1

In [3]:
data = [
    # Dog 1
    {
        "Type": "y",
        "1": 81.7,
        "2": 84.3,
        "3": 72.8,
        "4": 71.7,
        "5": 76.7,
        "6": 75.8,
        "7": 77.3,
        "8": 86.3,
    },
    {
        "Type": "x",
        "1": 54.3,
        "2": 62.0,
        "3": 62.3,
        "4": 47.3,
        "5": 53.6,
        "6": 38.0,
        "7": 54.2,
        "8": 54.0,
    },
    # Dog 2
    {
        "Type": "y",
        "1": 105.0,
        "2": 113.6,
        "3": 108.7,
        "4": 83.9,
        "5": 89.0,
        "6": 86.1,
        "7": 88.7,
        "8": 117.6,
    },
    {
        "Type": "x",
        "1": 81.5,
        "2": 80.8,
        "3": 74.5,
        "4": 71.9,
        "5": 79.5,
        "6": 73.0,
        "7": 74.7,
        "8": 88.6,
    },
    # Dog 3
    {
        "Type": "y",
        "1": 95.5,
        "2": 95.7,
        "3": 84.0,
        "4": 85.8,
        "5": 98.8,
        "6": 106.2,
        "7": 106.4,
        "8": 115.0,
    },
    {
        "Type": "x",
        "1": 65.0,
        "2": 68.3,
        "3": 67.9,
        "4": 61.0,
        "5": 66.0,
        "6": 81.8,
        "7": 71.4,
        "8": 96.0,
    },
    # Dog 4
    {
        "Type": "y",
        "1": 113.1,
        "2": 116.5,
        "3": 100.8,
        "4": 101.5,
        "5": 120.8,
        "6": 95.0,
        "7": 91.9,
        "8": 94.0,
    },
    {
        "Type": "x",
        "1": 87.5,
        "2": 93.6,
        "3": 70.4,
        "4": 66.1,
        "5": 101.4,
        "6": 57.0,
        "7": 82.5,
        "8": 80.9,
    },  # 第二版では97.5だが、第三版では87.5となっている.
    # Dog 5
    {
        "Type": "y",
        "1": 99.5,
        "2": 99.2,
        "3": 106.1,
        "4": 85.2,
        "5": 106.3,
        "6": 84.6,
        "7": 92.1,
        "8": 101.2,
    },
    {
        "Type": "x",
        "1": 79.4,
        "2": 82.5,
        "3": 87.9,
        "4": 66.4,
        "5": 68.4,
        "6": 59.5,
        "7": 58.5,
        "8": 69.2,
    },  # 第二版では59.4だが、第三版では68.4となっている.
]

# DataFrameを直接作成
df_flat = pd.DataFrame(data)

dog_index = [i for i in range(1, 6) for _ in range(2)]

# MultiIndex (階層型インデックス) を作成: DogとType (y/x)
index_tuples = list(zip(dog_index, df_flat["Type"]))
multi_index = pd.MultiIndex.from_tuples(index_tuples, names=["Dog", "Type"])

# インデックスを適用し、'Type'列を削除
df = df_flat.set_index(multi_index).drop(columns=["Type"]).reset_index()
df.columns = ["dog", "type"] + [f"condition_{i}" for i in range(1, 9)]

In [4]:
df

,dog,type,condition_1,condition_2,condition_3,condition_4,condition_5,condition_6,condition_7,condition_8
0,1,y,81.7,84.3,72.8,71.7,76.7,75.8,77.3,86.3
1,1,x,54.3,62.0,62.3,47.3,53.6,38.0,54.2,54.0
2,2,y,105.0,113.6,108.7,83.9,89.0,86.1,88.7,117.6
3,2,x,81.5,80.8,74.5,71.9,79.5,73.0,74.7,88.6
4,3,y,95.5,95.7,84.0,85.8,98.8,106.2,106.4,115.0
5,3,x,65.0,68.3,67.9,61.0,66.0,81.8,71.4,96.0
6,4,y,113.1,116.5,100.8,101.5,120.8,95.0,91.9,94.0
7,4,x,87.5,93.6,70.4,66.1,101.4,57.0,82.5,80.9
8,5,y,99.5,99.2,106.1,85.2,106.3,84.6,92.1,101.2
9,5,x,79.4,82.5,87.9,66.4,68.4,59.5,58.5,69.2


## (b)

In [5]:
df_long = df.melt(
    id_vars=["dog", "type"],
    value_vars=[f"condition_{i}" for i in range(1, 9)],
    var_name="condition",
    value_name="measurement",
)
df_result = df_long.pivot_table(
    index=["dog", "condition"], columns="type", values="measurement"
).reset_index()

# 3. カラム名の整理
df_result.columns.name = None
df_result = df_result.rename(columns={"x": "x", "y": "y"})

In [6]:
df_result.to_csv("dog_data_long_format.csv", index=False)

In [5]:
df_result

,dog,condition,x,y
0,1,condition_1,54.3,81.7
1,1,condition_2,62.0,84.3
2,1,condition_3,62.3,72.8
3,1,condition_4,47.3,71.7
4,1,condition_5,53.6,76.7
5,1,condition_6,38.0,75.8
6,1,condition_7,54.2,77.3
7,1,condition_8,54.0,86.3
8,2,condition_1,81.5,105.0
9,2,condition_2,80.8,113.6


## pooled analysis

In [6]:
X_pooled = df_result["x"].values
X_pooled = np.stack([np.ones(len(X_pooled)), X_pooled], axis=1)
y_pooled = df_result["y"].values

# 係数推定
beta_pooled = np.linalg.inv(X_pooled.T @ X_pooled) @ X_pooled.T @ y_pooled

# 不偏分散の推定
sigma_hat_sq = ((y_pooled - X_pooled @ beta_pooled) ** 2).sum() / (
    df_result.shape[0] - 2
)

# 標準誤差の推定
std_error_pooled = np.sqrt(np.diag(np.linalg.inv(X_pooled.T @ X_pooled)) * sigma_hat_sq)

# データフレームにまとめる
df_coef_pooled = pd.DataFrame(
    np.concatenate([beta_pooled, std_error_pooled]).reshape(4, 1)
).T
df_coef_pooled.columns = [
    "intercept",
    "slope",
    "std_error(intercept)",
    "std_error(coef)",
]
df_coef_pooled.index = ["pooled analyasis"]

In [7]:
df_coef_pooled

,intercept,slope,std_error(intercept),std_error(coef)
pooled analyasis,40.768083,0.769225,6.617261,0.091559


## データ縮約法による探索的解析

### dog と反応変数が独立の場合

In [8]:
list_coef = []
for dog, group in df_result.groupby("dog"):
    # デザイン行列の作成
    X_reduction = group["x"].values
    X_reduction = np.stack([np.ones(len(X_reduction)), X_reduction], axis=1)

    # 目的変数
    y_reduction = group["y"].values

    # 係数推定
    beta_reduction = (
        np.linalg.inv(X_reduction.T @ X_reduction) @ X_reduction.T @ y_reduction
    )
    beta_reduction = beta_reduction.tolist()

    # 不偏分散
    sigma_sq_hat = ((y_reduction - X_reduction @ beta_reduction) ** 2).sum() / (
        len(X_reduction) - 2
    )

    # 標準誤差
    std_error_reduction = np.sqrt(
        np.diag(np.linalg.inv(X_reduction.T @ X_reduction)) * sigma_sq_hat
    ).tolist()

    list_coef.append([dog] + beta_reduction + std_error_reduction)

df_coef_ignore_dog = pd.DataFrame(
    list_coef,
    columns=["dog", "intercept", "slope", "std_error(intercept)", "std_error(coef)"],
)

In [9]:
df_coef_ignore_dog

,dog,intercept,slope,std_error(intercept),std_error(coef)
0,1,67.389130,0.205513,14.085714,0.262235
1,2,-43.076229,1.820993,50.961668,0.651363
2,3,43.178247,0.765456,15.622221,0.214127
3,4,60.514328,0.546583,17.206281,0.212147
4,5,58.892430,0.530011,17.615007,0.244054


In [10]:
df_reduction_ignore_dog = (
    df_coef_ignore_dog.iloc[:, 1:]
    .mean()
    .to_frame()
    .rename(columns={0: "Data Reduction ignoring dog"})
    .T
)
df_reduction_ignore_dog

,intercept,slope,std_error(intercept),std_error(coef)
Data Reduction ignoring dog,37.379581,0.773711,23.098178,0.316785


### condition と反応変数が独立の場合

In [12]:
list_coef = []
for cond, group in df_result.groupby("condition"):
    # デザイン行列の作成
    X_reduction = group["x"].values
    X_reduction = np.stack([np.ones(len(X_reduction)), X_reduction], axis=1)

    # 目的変数
    y_reduction = group["y"].values

    # 係数推定
    beta_reduction = (
        np.linalg.inv(X_reduction.T @ X_reduction) @ X_reduction.T @ y_reduction
    )
    beta_reduction = beta_reduction.tolist()

    # 不偏分散
    sigma_sq_hat = ((y_reduction - X_reduction @ beta_reduction) ** 2).sum() / (
        len(X_reduction) - 2
    )

    # 標準誤差
    std_error_reduction = np.sqrt(
        np.diag(np.linalg.inv(X_reduction.T @ X_reduction)) * sigma_sq_hat
    ).tolist()
    list_coef.append([cond] + beta_reduction + std_error_reduction)

df_coef_ignore_cond = pd.DataFrame(
    list_coef,
    columns=[
        "condition",
        "intercept",
        "slope",
        "std_error(intercept)",
        "std_error(coef)",
    ],
)

In [13]:
df_coef_ignore_cond

,condition,intercept,slope,std_error(intercept),std_error(coef)
0,condition_1,37.957422,0.829516,10.079693,0.135237
1,condition_2,28.164018,0.951653,21.773720,0.278306
2,condition_3,3.718250,1.250162,42.600864,0.582705
3,condition_4,40.803707,0.716602,31.973300,0.506734
4,condition_5,43.670339,0.740711,24.691616,0.326993
5,condition_6,56.028782,0.541727,15.667583,0.246171
6,condition_7,62.799943,0.417229,31.271438,0.452837
7,condition_8,48.929136,0.693219,19.134660,0.241784


In [14]:
df_reduction_ignore_cond = (
    df_coef_ignore_cond.iloc[:, 1:]
    .mean()
    .to_frame()
    .rename(columns={0: "Data Reduction ignoring condition"})
    .T
)
df_reduction_ignore_cond

,intercept,slope,std_error(intercept),std_error(coef)
Data Reduction ignoring condition,40.25895,0.767602,24.649109,0.346346


## GEEモデルによる推定 

### dogがsubjectと仮定
https://www.maths.usyd.edu.au/u/jchan/GLM/Liang&Zeger1986GEE.pdf の(8)式による


In [65]:
df_result.groupby("dog").count()

,condition,x,y
dog,,,
1,8,8,8
2,8,8,8
3,8,8,8
4,8,8,8
5,8,8,8


In [344]:
def irls_for_gee(df_result, is_sandwitch, unbaised_variance):
    df_result = df_result.copy()

    # 初期値
    beta = np.array([1.0, 1.0])

    # 特徴量
    p = 2

    # 各被験者は8回の繰り返しがあり、dogの種類は5種類
    # 作業相関行列およびAの初期値は単位行列とする
    R = [np.eye(8) for _ in range(df_result["dog"].nunique())]
    A = [np.eye(8) for _ in range(df_result["dog"].nunique())]
    psi = 1

    # 10回IRLSで更新
    for iter_ in range(20):
        D = []
        V_inv = []
        S = []
        pearson_resid = []
        y = []

        for i, (dog, group) in enumerate(df_result.groupby("dog")):
            # muの勾配
            Di = np.stack([np.ones(len(group)), group["x"].values], axis=1)
            D.append(Di)

            # yiの推定
            # 実際には link function の逆関数を噛ませる必要があるが、
            # リンク関数として恒等関数を選択したのでそのままの値
            mu_i_hat = (Di * beta).sum(axis=1)

            # 第i groupにおける y の値
            yi = group["y"].values
            y.append(yi)

            # 残差
            resid = yi - mu_i_hat
            S.append(resid)

            # 正規分布の分散
            # 不偏分散を毎回iterごとに更新したものにするのも良いかも
            if unbaised_variance:
                variance = (resid**2).sum() / (8 - p)
            else:
                variance = 1

            # ピアソン残差
            ri = resid / np.sqrt(variance)
            pearson_resid.append(ri)

            # 分散の推定
            V_inv_i = np.sqrt(A[i]) @ R[i] @ np.sqrt(A[i]) * psi
            V_inv.append(np.linalg.inv(V_inv_i))

        if is_sandwitch:
            # 情報行列の計算
            J = np.zeros((2, 2))
            for i in range(len(D)):
                J += D[i].T @ V_inv[i] @ D[i]

            # Cの計算
            C = np.zeros((2, 2))
            for i in range(len(D)):
                C += D[i].T @ V_inv[i] @ np.outer(S[i], S[i]) @ V_inv[i] @ D[i]

            # サンドイッチ推定量
            std_error = np.linalg.inv(J) @ C @ np.linalg.inv(J)

        else:
            std_error = np.zeros((2, 2))
            for i in range(len(D)):
                std_error += D[i].T @ V_inv[i] @ D[i]
            std_error = np.linalg.inv(std_error)

        # subjectの数だけ足し合わせる
        mat_1 = np.zeros((2, 2))
        mat_2 = np.zeros((2, 1))
        for i in range(len(D)):
            mat_1 += D[i].T @ V_inv[i] @ D[i]
            mat_2 += D[i].T @ V_inv[i] @ S[i].reshape(8, 1)

        # IRLSによる更新
        beta += (np.linalg.inv(mat_1) @ mat_2).reshape(-1)

        # beta更新後にR, A, psiを更新する
        # mu_hat_i = (Di*beta).sum(axis = 1)
        psi = sum((pearson_resid[i] ** 2).sum() for i in range(len(pearson_resid))) / (
            len(df_result) - p
        )

        for i in range(len(pearson_resid)):
            Ri = np.outer(pearson_resid[i], pearson_resid[i]) / (len(df_result) - p)
            R[i] = Ri
            A[i] = np.diag(np.diag(Ri))

    return beta, np.diag(std_error)

In [345]:
is_sandwitch = True
unbaised_variance = True
beta, std_error = irls_for_gee(df_result, is_sandwitch, unbaised_variance)

LinAlgError: Singular matrix

In [343]:
beta

array([nan, nan])

In [340]:
std_error

array([2.0464268e+01, 2.6822283e-03])

In [299]:
is_sandwich = False
beta, std_error = irls_for_gee(df_result, is_sandwich, max_iter=10, tol=1e-6)

/var/folders/g4/gx0098gn4072x6j58_7tw_8c0000gn/T/ipykernel_80069/57428487.py:120: RuntimeWarning: invalid value encountered in sqrt
  return beta, np.sqrt(np.diag(cov_beta))  # beta, std errors (vector)


In [300]:
beta

array([275.11710011,  -1.97728098])

In [302]:
std_error

array([nan, nan])

In [251]:
R

[1,
 array([[1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.]]),
 array([[1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.]]),
 array([[1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0